import { useState } from 'react';
import { Link, NavLink, useSearchParams } from 'react-router-dom';
import { loadSnapshot } from '../../data/reports/snapshot';
import { financeRepository } from '../../data/finance';
import { accountBalances, accountKey, expenseCategories, outstandingEntries } from '../../domain/finance';
import type { Expense, ManualDebt } from '../../domain/finance';
import { accountName, selectAccountEntries } from '../../domain/accountSelectors';
import { paymentMethods } from '../../domain/common';
import type { PaymentMethod } from '../../domain/common';
import { displayDate, money, today } from '../products/model';
import { CompanySelect, Form, Input, Page, Section, Select, Table, numeric, text, useResource } from '../shared/WorkshopUI';
import { AccountSelect, PaymentForm } from './PaymentForm';
import { AdjustmentForm } from './AdjustmentForm';

export function FinancePage({ page }: { page: 'accounts' | 'payments-made' | 'payments-received' | 'debts' | 'receivables' | 'expenses' }) {
  const resource = useResource(loadSnapshot); const data = resource.data; const [params, setParams] = useSearchParams(); const [form, setForm] = useState('');
  const selected = params.get('firma') ? accountKey(params.get('firma')!, params.get('sorumlu') ?? '') : '';
  const entries = data ? selectAccountEntries(data) : []; const balances = accountBalances(entries); const debt = page === 'debts'; const payments = page.startsWith('payments');
  const title = { accounts: 'Cari Hesaplar', 'payments-made': 'Para Hareketleri', 'payments-received': 'Para Hareketleri', debts: 'Borç Listesi', receivables: 'Alacak Listesi', expenses: 'Genel Giderler' }[page];
  const done = () => { resource.reload(); setForm(''); };
  const accountEntries = entries.filter((e) => accountKey(e.companyId, e.responsibleId) === selected); let balance = 0;
  return <Page title={title} error={resource.error} loading={!data && !resource.error} reload={resource.reload}>{data && <>
    {!!data.errors.length && <p className="ws-error" role="alert">Bazı kaynaklar okunamadı; aşağıdaki tutarlar eksik olabilir. {data.errors.join(' ')}</p>}
    {page === 'accounts' && <><div className="ws-filters"><AccountSelect data={data} value={selected} onChange={(value) => { const [firma, sorumlu] = value.split('|'); setParams(firma ? { firma, sorumlu: sorumlu || '' } : {}); setForm(''); }} /></div>
      {selected ? <><div className="ws-tabs"><button className="button" onClick={() => setForm('paid')}>Ödeme Yap</button><button className="button" onClick={() => setForm('received')}>Tahsilat Gir</button><button className="button ws-secondary" onClick={() => setForm('adjustment')}>Mahsup / Diğer</button></div>{form === 'adjustment' && <AdjustmentForm account={selected} done={done} />}{['paid', 'received'].includes(form) && <PaymentForm key={`${form}-${selected}`} data={data} direction={form as 'paid' | 'received'} defaultAccount={selected} done={done} />}<Table headers={['Tarih', 'Kaynak', 'Açıklama', 'Borç', 'Alacak', 'Bakiye', 'Kaynak Kayıt']} rows={accountEntries.map((e) => { balance += e.deltaMinor; return [displayDate(e.date), e.source, e.description, e.deltaMinor < 0 ? money(-e.deltaMinor) : '—', e.deltaMinor > 0 ? money(e.deltaMinor) : '—', `${money(Math.abs(balance))} ${balance < 0 ? 'Borç' : balance > 0 ? 'Alacak' : ''}`, <Link to={e.href}>{e.sourceId}</Link>]; })} /><p className="ws-hint">Borç: bizim ödememiz gereken tutar. Alacak: bize ödenecek tutar. Ödeme borcu, tahsilat alacağı azaltır; bakiye karşılıklı netleştirilir.</p></>
      : <Table headers={['Firma / Kişi', 'Borç', 'Alacak', 'İşlemler']} rows={[...data.contacts.map((c) => ({ companyId: c.id, responsibleId: '', balance: balances.find((b) => b.companyId === c.id)?.balance ?? 0 })), ...balances.filter((b) => b.responsibleId)].map((b) => [accountName(data, b.companyId, b.responsibleId), money(Math.max(-b.balance, 0)), money(Math.max(b.balance, 0)), <Link className="button ws-secondary" to={`/finans/cari-hesaplar?firma=${b.companyId}&sorumlu=${b.responsibleId}`}>Cari Detay</Link>])} />}</>}
    {payments && <><div className="ws-tabs"><NavLink to="/finans/yapilan-odemeler">Yapılan Ödemeler</NavLink><NavLink to="/finans/alinan-odemeler">Alınan Ödemeler</NavLink><button className="button" onClick={() => setForm(form ? '' : 'payment')}>Yeni {page === 'payments-made' ? 'Yapılan' : 'Alınan'} Ödeme</button></div>{form && <PaymentForm key={page} data={data} direction={page === 'payments-made' ? 'paid' : 'received'} done={done} />}<Table headers={['Tarih', page === 'payments-made' ? 'Kime' : 'Kimden', 'Tutar', 'Ödeme Şekli', 'Açıklama', 'Kaynak Kayıt']} rows={(data.finance?.moneyMovements ?? []).filter((m) => m.direction === (page === 'payments-made' ? 'paid' : 'received')).map((m) => [displayDate(m.date), accountName(data, m.companyId, m.responsibleId), money(m.amountMinor), m.method, m.description, <Link to={`/finans/cari-hesaplar?firma=${m.companyId}&sorumlu=${m.responsibleId}`}>{m.id}</Link>])} /></>}
    {(page === 'debts' || page === 'receivables') && <><div className="ws-tabs"><button className="button" onClick={() => setForm(form ? '' : 'loan')}>{debt ? 'Alınan Borç' : 'Verilen Borç'} Ekle</button></div>{form && <Section title={debt ? 'Alınan Borç' : 'Verilen Borç'}><Form onDone={done} onSubmit={(f) => financeRepository.loan({ companyId: text(f, 'companyId'), type: (debt ? 'Alınan Borç' : 'Verilen Borç') as ManualDebt['type'], amount: numeric(f, 'amount'), date: text(f, 'date'), description: text(f, 'description'), source: text(f, 'source') })}><div className="ws-grid"><CompanySelect contacts={data.contacts} required /><Input label="Tutar (TL) *" name="amount" type="number" min="0.01" step="0.01" required /><Input label="Tarih *" name="date" type="date" value={today()} required /><Input label="Kaynak *" name="source" required /><Input label="Açıklama *" name="description" required /></div></Form></Section>}<Table headers={['Firma', 'Tutar', 'Kaynak', 'Tarih', 'Açıklama', 'Kalan']} rows={outstandingEntries(entries).filter((row) => debt ? row.remaining < 0 : row.remaining > 0).map(({ entry: e, remaining }) => [accountName(data, e.companyId, e.responsibleId), money(Math.abs(e.deltaMinor)), <Link to={e.href}>{e.source === 'Alınan Borç' || e.source === 'Verilen Borç' ? e.source : `Cari Hesap / ${e.source}`}</Link>, displayDate(e.date), e.description, money(Math.abs(remaining))])} /><p className="ws-hint">Karşılıklı hareketler firma bazında netleştirilir. Kalan tutarlar en eski kaynak önce kapanacak şekilde hesaplanır.</p></>}
    {page === 'expenses' && <><div className="ws-tabs"><button className="button" onClick={() => setForm(form ? '' : 'expense')}>Yeni Genel Gider</button></div>{form && <Section title="Genel Gider"><Form onDone={done} onSubmit={(f) => financeRepository.expense({ date: text(f, 'date'), category: text(f, 'category') as Expense['category'], description: text(f, 'description'), amount: numeric(f, 'amount'), method: text(f, 'method') as PaymentMethod, companyId: text(f, 'companyId'), note: text(f, 'note') })}><div className="ws-grid"><Input label="Tarih *" name="date" type="date" value={today()} required /><Select label="Gider Türü" name="category" values={expenseCategories} /><Input label="Açıklama *" name="description" required /><Input label="Tutar (TL) *" name="amount" type="number" min="0.01" step="0.01" required /><Select label="Ödeme Şekli" name="method" values={paymentMethods} /><CompanySelect contacts={data.contacts} /><Input label="Not" name="note" /></div><p className="ws-hint">Bu form ödenmiş genel gideri kaydeder; ayrıca cari borç veya ödeme kaydı oluşturmaz. Stok alımı ve fason ödemelerini burada tekrar girmeyin.</p></Form></Section>}<Table headers={['Tarih', 'Gider Türü', 'Açıklama', 'Tutar', 'Ödeme Şekli', 'Firma / Kişi', 'Not']} rows={(data.finance?.expenses ?? []).map((e) => [displayDate(e.date), e.category, e.description, money(e.amountMinor), e.method, e.companyId ? accountName(data, e.companyId) : '—', e.note])} /></>}
  </>}</Page>;
}
