import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { inventory } from '../../data/inventory';
import type { AccountChoice } from '../../domain/common';
import { displayDate, money, number, today } from '../products/model';
import { AccountChoiceField, Action, CompanySelect, Field, Form, Input, Page, Section, Table, companyName, numeric, text, useCompanies, useResource } from '../shared/WorkshopUI';

export function FabricsPage() {
  const resource = useResource(inventory.fabrics.load); const companies = useCompanies();
  const [params] = useSearchParams();
  const [create, setCreate] = useState(false); const [selected, setSelected] = useState(params.get('kayit') ?? ''); const [search, setSearch] = useState('');
  const [rows, setRows] = useState([{ color: '', rolls: 1, kg: 0 }]); const [price, setPrice] = useState(0);
  const item = resource.data?.records.find((record) => record.id === selected);
  const done = () => { setCreate(false); resource.reload(); };
  const kg = rows.reduce((sum, row) => sum + (row.kg || 0), 0); const rolls = rows.reduce((sum, row) => sum + (row.rolls || 0), 0);
  return <Page title="Stoktaki Kumaşlar" error={resource.error || companies.error} loading={!resource.data && !resource.error} reload={resource.reload}>
    <div className="ws-tabs"><button className="button ws-secondary" onClick={() => { setCreate(false); setSelected(''); }}>Liste</button><button className="button" disabled={!companies.data || !!resource.error} onClick={() => { setCreate(true); setSelected(''); setRows([{ color: '', rolls: 1, kg: 0 }]); setPrice(0); }}>Yeni Kumaş Girişi</button></div>
    {create ? <Form onDone={done} onSubmit={(form) => inventory.fabrics.create({ name: text(form, 'name'), grammage: text(form, 'grammage'), content: text(form, 'content'), width: text(form, 'width'), lot: text(form, 'lot'), date: text(form, 'date'), companyId: text(form, 'companyId'), price, note: text(form, 'note'), account: text(form, 'account') as AccountChoice, colors: rows })}>
      <Section title="Kumaş Bilgileri"><div className="ws-grid"><Input label="Kumaş Adı *" name="name" required /><Input label="Gramaj" name="grammage" /><Input label="İçerik" name="content" /><Input label="En" name="width" /><Input label="Lot / Parti No *" name="lot" required /><Input label="Giriş Tarihi *" name="date" type="date" value={today()} required /><CompanySelect contacts={companies.data ?? []} role="Kumaş Tedarikçisi" /><Field label="Kg Alış Fiyatı (TL) *"><input type="number" min="0" step="0.01" value={Number.isNaN(price) ? '' : price} required onChange={(event) => setPrice(event.target.valueAsNumber)} /></Field><AccountChoiceField /><Input label="Not" name="note" /></div></Section>
      <Section title="Renk Dağılımı">{rows.map((row, index) => <div className="ws-row" key={index}><Field label="Renk *"><input required value={row.color} onChange={(event) => setRows(rows.map((r, i) => i === index ? { ...r, color: event.target.value } : r))} /></Field><Field label="Top Sayısı *"><input required type="number" min="1" step="1" value={Number.isNaN(row.rolls) ? '' : row.rolls} onChange={(event) => setRows(rows.map((r, i) => i === index ? { ...r, rolls: event.target.valueAsNumber } : r))} /></Field><Field label="Kg *"><input required type="number" min="0.001" step="0.001" value={row.kg || ''} onChange={(event) => setRows(rows.map((r, i) => i === index ? { ...r, kg: event.target.valueAsNumber } : r))} /></Field><button type="button" className="button ws-secondary" disabled={rows.length === 1} onClick={() => setRows(rows.filter((_, i) => i !== index))}>Satırı Kaldır</button></div>)}<button type="button" className="button ws-secondary" onClick={() => setRows([...rows, { color: '', rolls: 1, kg: 0 }])}>+ Renk Ekle</button><p className="ws-hint">Toplam: {number(rolls)} top · {number(kg)} kg · {money(Math.round(kg * (price || 0) * 100))}</p></Section>
    </Form> : item ? <>
      <Section title={`${item.name} · ${item.lot}`}><p className="ws-hint">Gramaj: {item.grammage || '—'} · İçerik: {item.content || '—'} · En: {item.width || '—'} · {companyName(companies.data, item.companyId)} · {item.note}</p><Table headers={['Renk', 'Top', 'Kg']} rows={item.colors.map((color) => [color.color, number(color.rolls), number(color.kg)])} /><div className="ws-actions"><Action run={() => inventory.fabrics.toggle(item.id)} done={done}>{item.active ? 'Pasif Yap' : 'Aktif Yap'}</Action></div></Section>
      {item.active && <Section title="Stok Düzelt"><Form key={item.id} onDone={done} onSubmit={(form) => inventory.fabrics.adjust(item.id, text(form, 'colorId'), numeric(form, 'kg'), numeric(form, 'rolls'), text(form, 'date'), text(form, 'description'))}><div className="ws-grid"><Field label="Renk"><select name="colorId">{item.colors.map((color) => <option key={color.id} value={color.id}>{color.color}</option>)}</select></Field><Input label="Yeni Top Sayısı *" name="rolls" type="number" min="0" step="1" required /><Input label="Yeni Kg *" name="kg" type="number" min="0" step="0.001" required /><Input label="Tarih *" name="date" type="date" value={today()} required /><Input label="Açıklama *" name="description" required /></div></Form></Section>}
      <Section title="Hareket Geçmişi"><Table headers={['Tarih', 'Renk', 'İşlem', 'Giriş Kg', 'Çıkış Kg', 'Kalan Kg', 'Top Değişimi', 'Kalan Top', 'Açıklama']} rows={(resource.data?.movements ?? []).filter((m) => m.recordId === item.id).map((m) => [displayDate(m.date), item.colors.find((c) => c.id === m.colorId)?.color, m.type, number(m.incoming), number(m.outgoing), number(m.balance), m.rollDelta, m.rollBalance, m.description])} /></Section>
    </> : <><div className="ws-filters"><Field label="Ara"><input value={search} onChange={(event) => setSearch(event.target.value)} /></Field></div><Table headers={['Kumaş', 'Lot / Parti', 'Renkler', 'Toplam Top', 'Toplam Kg', 'Alış Tutarı', 'Tedarikçi', 'Durum', 'İşlemler']} rows={(resource.data?.records ?? []).filter((r) => `${r.name} ${r.lot}`.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))).map((r) => [r.name, r.lot, r.colors.map((c) => c.color).join(', '), number(r.colors.reduce((s, c) => s + c.rolls, 0)), number(r.colors.reduce((s, c) => s + c.kg, 0)), money(r.purchaseMinor), companyName(companies.data, r.companyId), r.active ? 'Aktif' : 'Pasif', <button onClick={() => setSelected(r.id)} className="button ws-secondary">Detay / Hareketler</button>])} /></>}
  </Page>;
}
