import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { inventory } from '../../data/inventory';
import type { AccountChoice } from '../../domain/common';
import { materialCategories, units } from '../../domain/inventory';
import type { InventoryMovement, Material } from '../../domain/inventory';
import { displayDate, money, number, today } from '../products/model';
import { AccountChoiceField, Action, CompanySelect, Field, Form, Input, Page, Section, Select, Table, companyName, numeric, text, useCompanies, useResource } from '../shared/WorkshopUI';

export function MaterialsPage() {
  const resource = useResource(inventory.materials.load); const companies = useCompanies();
  const [params] = useSearchParams();
  const [create, setCreate] = useState(false); const [selected, setSelected] = useState(params.get('kayit') ?? ''); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [qty, setQty] = useState(1); const [price, setPrice] = useState(0);
  const item = resource.data?.records.find((r) => r.id === selected); const done = () => { setCreate(false); resource.reload(); };
  return <Page title="Stoktaki Malzemeler" error={resource.error || companies.error} loading={!resource.data && !resource.error} reload={resource.reload}>
    <div className="ws-tabs"><button className="button ws-secondary" onClick={() => { setCreate(false); setSelected(''); }}>Liste</button><button className="button" disabled={!companies.data || !!resource.error} onClick={() => { setCreate(true); setSelected(''); setQty(1); setPrice(0); }}>Yeni Malzeme Girişi</button></div>
    {create ? <Form onDone={done} onSubmit={(f) => inventory.materials.create({ name: text(f, 'name'), category: text(f, 'category') as Material['category'], feature: text(f, 'feature'), quantity: qty, unit: text(f, 'unit') as Material['unit'], price, companyId: text(f, 'companyId'), date: text(f, 'date'), note: text(f, 'note'), account: text(f, 'account') as AccountChoice })}><Section title="Malzeme Bilgileri"><div className="ws-grid"><Input label="Malzeme Adı *" name="name" required /><Select label="Kategori" name="category" values={materialCategories} /><Input label="Renk / Özellik" name="feature" /><Select label="Birim" name="unit" values={units} /><Field label="Miktar *"><input type="number" min="0.001" step="0.001" required value={qty || ''} onChange={(e) => setQty(e.target.valueAsNumber)} /></Field><Field label="Birim Alış Fiyatı (TL) *"><input type="number" min="0" step="0.01" required value={Number.isNaN(price) ? '' : price} onChange={(e) => setPrice(e.target.valueAsNumber)} /></Field><CompanySelect contacts={companies.data ?? []} role="Malzeme Tedarikçisi" /><Input label="Giriş Tarihi *" name="date" type="date" value={today()} required /><AccountChoiceField /><Input label="Not" name="note" /></div><p className="ws-hint">Toplam tutar: {money(Math.round((qty || 0) * (price || 0) * 100))}</p></Section></Form>
    : item ? <><Section title={item.name}><p className="ws-hint">{item.category} · {item.feature} · {number(item.quantity)} {item.unit} · {companyName(companies.data, item.companyId)} · {item.note}</p><Action run={() => inventory.materials.toggle(item.id)} done={done}>{item.active ? 'Pasif Yap' : 'Aktif Yap'}</Action></Section>
    {item.active && <Section title="Stok Hareketi"><Form key={item.id} onDone={done} onSubmit={(f) => inventory.materials.move(item.id, text(f, 'type') as InventoryMovement['type'], numeric(f, 'quantity'), text(f, 'date'), text(f, 'description'))}><div className="ws-grid"><Select label="İşlem" name="type" values={['Giriş', 'Çıkış', 'Sayım / Düzeltme', 'İade']} /><Input label="Miktar (düzeltmede yeni toplam) *" name="quantity" type="number" min="0" step="0.001" required /><Input label="Tarih *" name="date" type="date" required value={today()} /><Input label="Açıklama *" name="description" required /></div><p className="ws-hint">İade stoktan düşer. Bu hareketler yalnızca miktarı değiştirir; yeni alım için Yeni Malzeme Girişi kullanın.</p></Form></Section>}
    <Section title="Hareket Geçmişi"><Table headers={['Tarih', 'İşlem', 'Giriş', 'Çıkış', 'Kalan', 'Açıklama']} rows={(resource.data?.movements ?? []).filter((m) => m.recordId === item.id).map((m) => [displayDate(m.date), m.type, number(m.incoming), number(m.outgoing), `${number(m.balance)} ${item.unit}`, m.description])} /></Section></>
    : <><div className="ws-filters"><Field label="Ara"><input value={search} onChange={(e) => setSearch(e.target.value)} /></Field><Field label="Kategori"><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Tümü</option>{materialCategories.map((c) => <option key={c}>{c}</option>)}</select></Field></div><Table headers={['Malzeme', 'Kategori', 'Renk / Özellik', 'Miktar', 'Birim Fiyat', 'Alış Tutarı', 'Tedarikçi', 'Durum', 'İşlemler']} rows={(resource.data?.records ?? []).filter((r) => r.name.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')) && (!category || r.category === category)).map((r) => [r.name, r.category, r.feature, `${number(r.quantity)} ${r.unit}`, money(r.priceMinor), money(r.purchaseMinor), companyName(companies.data, r.companyId), r.active ? 'Aktif' : 'Pasif', <button className="button ws-secondary" onClick={() => setSelected(r.id)}>Detay / Hareketler</button>])} /></>}
  </Page>;
}
