import type { CostPrices } from '../../domain/productionCosts';
import { costMoney } from '../../domain/productionCosts';
import { accessoryAvailability, accessoryUnits, extraCostCategories } from '../../domain/orderCosting';
import type { OrderCosting } from '../../domain/orderCosting';
import type { PlanStage } from '../../domain/productionPlan';
import type { Contact } from '../contacts/model';
import type { Material } from '../../domain/inventory';
import { Field } from '../shared/WorkshopUI';

export function OrderCostFields({ prices, costing, stages, contacts, materials, date, onPrices, onCosting }: { prices: CostPrices; costing: OrderCosting; stages: PlanStage[]; contacts: Contact[]; materials: Material[]; date: string; onPrices: (p: CostPrices) => void; onCosting: (v: OrderCosting) => void }) {
  const firms = (value: string, change: (v: string) => void, label: string, disabled = false) => <select aria-label={label} value={value} disabled={disabled} onChange={(e) => change(e.target.value)}><option value="">Cari bağlantısı yok</option>{contacts.filter((c) => c.status === 'Aktif' || c.id === value).map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select>;
  const available = accessoryAvailability(costing.accessories, materials);
  return <><div className="order-cost-prices">{(['Kumaş', ...stages] as const).map((key) => <Field key={key} label={key === 'Kumaş' ? 'Kumaş Kg Fiyatı (TL)' : `${key === 'Ütü & Paket' ? 'Ütü / Paket' : key === 'Nakış' || key === 'Baskı' ? `Uygulama · ${key}` : key} Birim Fiyatı (TL)`}><input aria-label={`${key} Birim Fiyatı`} type="number" min="0" step="0.01" value={prices[key] === undefined ? '' : prices[key]! / 100} onChange={(e) => { const next = { ...prices }; if (e.target.value === '') delete next[key]; else next[key] = Math.round(Number(e.target.value) * 100); onPrices(next); }} /></Field>)}</div>
    <Field label="Kumaş Tedarikçisi / Cari">{firms(costing.fabricCompanyId, (fabricCompanyId) => onCosting({ ...costing, fabricCompanyId }), 'Kumaş Tedarikçisi / Cari')}</Field>
    <h3>Gerekli Aksesuarlar</h3><div className="order-accessories">{costing.accessories.map((r, i) => { const material = materials.find((m) => m.id === r.materialId); return <div className="order-accessory-row" key={r.id}>
      <Field label={`Aksesuar ${i+1} Adı`}><input required maxLength={200} value={r.name} onChange={(e) => onCosting({ ...costing, accessories: costing.accessories.map((v) => v.id === r.id ? { ...v, name: e.target.value } : v) })} /></Field>
      <Field label={`Aksesuar ${i+1} Miktar`}><input required type="number" min={['Adet','Paket'].includes(r.unit) ? '1' : '0.001'} step={['Adet','Paket'].includes(r.unit) ? '1' : '0.001'} value={r.quantity || ''} onChange={(e) => onCosting({ ...costing, accessories: costing.accessories.map((v) => v.id === r.id ? { ...v, quantity: Number(e.target.value) } : v) })} /></Field>
      <Field label={`Aksesuar ${i+1} Birim`}><select value={r.unit} disabled={!!r.materialId} onChange={(e) => onCosting({ ...costing, accessories: costing.accessories.map((v) => v.id === r.id ? { ...v, unit: e.target.value as typeof r.unit } : v) })}>{accessoryUnits.map((u) => <option key={u}>{u}</option>)}</select></Field>
      <Field label={`Aksesuar ${i+1} Stok`}><select value={r.materialId} onChange={(e) => { const m = materials.find((v) => v.id === e.target.value); onCosting({ ...costing, accessories: costing.accessories.map((v) => v.id === r.id ? { ...v, materialId: e.target.value, ...(m ? { name: v.name || m.name, unit: m.unit as typeof r.unit } : {}) } : v) }); }}><option value="">Tedarik / stok dışı</option>{materials.filter((m) => (m.active || m.id === r.materialId) && accessoryUnits.includes(m.unit as typeof r.unit)).map((m) => <option key={m.id} value={m.id}>{m.name} · {m.quantity} {m.unit}</option>)}</select></Field>
      <Field label={`Aksesuar ${i+1} Birim Fiyatı`}><input type="number" min="0" step="0.01" disabled={!!r.materialId} value={(material?.priceMinor ?? r.priceMinor) === undefined ? '' : (material?.priceMinor ?? r.priceMinor!) / 100} onChange={(e) => onCosting({ ...costing, accessories: costing.accessories.map((v) => v.id === r.id ? { ...v, priceMinor: e.target.value === '' ? undefined : Math.round(Number(e.target.value) * 100) } : v) })} /></Field>
      <Field label={`Aksesuar ${i+1} Tedarikçi`}>{firms(material?.companyId ?? r.companyId, (companyId) => onCosting({ ...costing, accessories: costing.accessories.map((v) => v.id === r.id ? { ...v, companyId } : v) }), `Aksesuar ${i+1} Tedarikçi`, !!r.materialId)}</Field>
      <p>Mevcut: {available[i].available} · Eksik: <strong>{available[i].missing} {r.unit}</strong>{r.materialId && ' · Stok alımı caride tekrar oluşturulmaz.'}</p><button type="button" className="button ws-secondary compact-control" aria-label={`Aksesuar ${i+1} sil`} onClick={() => onCosting({ ...costing, accessories: costing.accessories.filter((v) => v.id !== r.id) })}>−</button>
    </div>; })}</div><button type="button" className="button ws-secondary" disabled={costing.accessories.length >= 100} onClick={() => onCosting({ ...costing, accessories: [...costing.accessories, { id: crypto.randomUUID(), name: '', quantity: 0, unit: 'Adet', materialId: '', companyId: '' }] })}>+ Aksesuar Ekle</button>
    <p className="ws-hint">Stok eşleştirmesi ihtiyacı ve eksik miktarı gösterir; stok çıkışı yapmaz. Stok dışı alım fiyatı ve tedarikçisi kaydedildiğinde tutar maliyete ve cariye yansır.</p>
    <h3>Ek Maliyetler</h3>{costing.extras.map((r,i) => <div className="order-extra-cost-row" key={r.id}>
      <Field label={`Ek Maliyet ${i+1} Türü`}><select value={r.category} onChange={(e) => onCosting({ ...costing, extras: costing.extras.map((v) => v.id === r.id ? { ...v, category: e.target.value as typeof r.category } : v) })}>{extraCostCategories.map((c) => <option key={c}>{c}</option>)}</select></Field>
      <Field label={`Ek Maliyet ${i+1} Açıklama`}><input required maxLength={200} value={r.name} onChange={(e) => onCosting({ ...costing, extras: costing.extras.map((v) => v.id === r.id ? { ...v, name: e.target.value } : v) })} /></Field>
      <Field label={`Ek Maliyet ${i+1} Tutar (TL)`}><input required type="number" min="0" step="0.01" value={r.amountMinor/100} onChange={(e) => onCosting({ ...costing, extras: costing.extras.map((v) => v.id === r.id ? { ...v, amountMinor: Math.round(Number(e.target.value)*100) } : v) })} /></Field>
      <Field label={`Ek Maliyet ${i+1} Firma`}>{firms(r.companyId, (companyId) => onCosting({ ...costing, extras: costing.extras.map((v) => v.id === r.id ? { ...v, companyId } : v) }), `Ek Maliyet ${i+1} Firma`)}</Field>
      <Field label={`Ek Maliyet ${i+1} Tarih`}><input required type="date" value={r.date} onChange={(e) => onCosting({ ...costing, extras: costing.extras.map((v) => v.id === r.id ? { ...v, date: e.target.value } : v) })} /></Field>
      <button type="button" className="button ws-secondary compact-control" aria-label={`Ek Maliyet ${i+1} sil`} onClick={() => onCosting({ ...costing, extras: costing.extras.filter((v) => v.id !== r.id) })}>−</button>
    </div>)}<button type="button" className="button ws-secondary" disabled={costing.extras.length >= 100} onClick={() => onCosting({ ...costing, extras: [...costing.extras, { id: crypto.randomUUID(), category: 'Diğer', name: '', amountMinor: 0, companyId: '', date }] })}>+ Ek Maliyet Ekle</button><p className="ws-hint">Ek maliyet toplamı: {costMoney(costing.extras.reduce((n,r) => n+r.amountMinor,0))}. Aynı aksesuarı ek maliyet olarak tekrar girmeyin.</p>
  </>;
}
