import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { workflowRepository } from '../../data/production';
import { productDefinitionRepository } from '../../data/productDefinitions';
import { contactRepository } from '../../data/contacts';
import type { ContactInput } from '../contacts/model';
import type { ProductionOrderCard, ProductionOrderItem } from '../../domain/productionWorkflow';
import { NewProductionForm } from './ProductionForms';
import { Field, Form, Input, Page, Section, Table, text, useCompanies, useResource } from '../shared/WorkshopUI';
import { today } from '../products/model';
import './production.css';

type DraftItem = Omit<ProductionOrderItem, 'id' | 'productName' | 'totalQuantity'>;
const emptyItem = (): DraftItem => ({ productDefinitionId: '', colorQuantities: [{ color: '', quantity: 0 }], fabricName: '', gsm: '', fabricProperties: '', productDetails: '' });
const total = (item: DraftItem | ProductionOrderItem) => item.colorQuantities.reduce((sum, row) => sum + (Number(row.quantity) || 0), 0);

function CustomerQuickAdd({ done }: { done: (id: string) => void }) {
  return <Section title="Yeni Müşteri Ekle"><Form onDone={() => {}} onSubmit={async (form) => { const input: ContactInput = { type: 'Firma', name: text(form, 'name'), authorizedPerson: '', phone: '', email: '', address: '', note: '', taxOffice: '', taxNumber: '', billingAddress: '', invoiceStatus: '', roles: ['Hazır Giyim Müşterisi'], services: [], status: 'Aktif' }; const saved = await contactRepository.create(input); done(saved.id); }}><Input label="Müşteri / Firma Adı *" name="name" required /></Form></Section>;
}
function ItemEditor({ item, definitions, update, remove }: { item: DraftItem; definitions: { id: string; name: string; status: string }[]; update: (item: DraftItem) => void; remove: () => void }) {
  const setColor = (index: number, field: 'color' | 'quantity', value: string) => update({ ...item, colorQuantities: item.colorQuantities.map((row, i) => i === index ? { ...row, [field]: field === 'quantity' ? Number(value) : value } : row) });
  return <div className="production-brand-editor"><Field label="Ürün *"><select value={item.productDefinitionId} onChange={(e) => update({ ...item, productDefinitionId: e.target.value })} required><option value="">Ürün seçin</option>{definitions.filter((d) => d.status === 'Aktif').map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><strong>Renk Dağılımı</strong>{item.colorQuantities.map((row, i) => <div className="production-color-editor" key={i}><Field label="Renk *"><input value={row.color} onChange={(e) => setColor(i, 'color', e.target.value)} required /></Field><Field label="Adet *"><input type="number" min={1} step={1} value={row.quantity || ''} onChange={(e) => setColor(i, 'quantity', e.target.value)} required /></Field>{item.colorQuantities.length > 1 && <button type="button" className="button ws-secondary" onClick={() => update({ ...item, colorQuantities: item.colorQuantities.filter((_, index) => index !== i) })}>Satırı Sil</button>}</div>)}<button type="button" className="button ws-secondary" onClick={() => update({ ...item, colorQuantities: [...item.colorQuantities, { color: '', quantity: 0 }] })}>+ Renk Ekle</button><p className="ws-hint">Toplam Sipariş Adedi: {total(item)}</p><div className="ws-grid"><Input label="Kumaş Adı *" name={`fabricName-${item.productDefinitionId}`} value={item.fabricName} required /><Input label="Gramaj *" name={`gsm-${item.productDefinitionId}`} value={item.gsm} required /><Field label="Kumaş Özellikleri"><textarea value={item.fabricProperties} onChange={(e) => update({ ...item, fabricProperties: e.target.value })} rows={2} /></Field><Field label="Ürüne Ait Özellikler / Talimatlar"><textarea value={item.productDetails} onChange={(e) => update({ ...item, productDetails: e.target.value })} rows={3} /></Field></div><button type="button" className="button ws-secondary" onClick={remove}>Sipariş Kalemini Kaldır</button></div>;
}

export function OrderCardsPage() {
  const resource = useResource(async () => ({ orders: await workflowRepository.listOrders(), cards: await workflowRepository.list(), definitions: await productDefinitionRepository.list() }));
  const companies = useCompanies(); const [params, setParams] = useSearchParams(); const [creating, setCreating] = useState(false); const [quickCustomer, setQuickCustomer] = useState(false); const [newCustomerId, setNewCustomerId] = useState(''); const [items, setItems] = useState<DraftItem[]>([emptyItem()]); const [selectedItem, setSelectedItem] = useState('');
  const order = resource.data?.orders.find((o) => o.id === params.get('id')); const definitions = resource.data?.definitions ?? []; const cards = resource.data?.cards ?? [];
  const itemUsage = (item: ProductionOrderItem) => item.colorQuantities.map((row) => { const used = cards.filter((card) => card.orderItemId === item.id).flatMap((card) => card.selectedColorQuantities ?? []).filter((selected) => selected.color.trim().toLocaleLowerCase('tr-TR') === row.color.trim().toLocaleLowerCase('tr-TR')).reduce((sum, selected) => sum + selected.quantity, 0); return `${row.color}: ${row.quantity} / ${used} / ${row.quantity - used}`; }).join(' · ');
  const customers = useMemo(() => (companies.data ?? []).filter((c) => c.status === 'Aktif'), [companies.data]);
  if (order) return <Page title={`${order.orderNo} · Sipariş Kartı`} error={resource.error || companies.error} loading={!resource.data || !companies.data} reload={resource.reload}><div className="ws-tabs"><button className="button ws-secondary" onClick={() => setParams({})}>Sipariş Kartlarına Dön</button><button className="button" onClick={() => setCreating(!creating)}>+ Üretim Kartı Oluştur</button></div><Section title="Sipariş Bilgileri"><dl className="production-summary"><div><dt>Sipariş No</dt><dd>{order.orderNo}</dd></div><div><dt>Sipariş Türü</dt><dd>{order.orderType}</dd></div><div><dt>Tarih</dt><dd>{order.date}</dd></div><div><dt>Müşteri</dt><dd>{companies.data?.find((c) => c.id === order.customerId)?.name ?? '—'}</dd></div><div><dt>Not</dt><dd>{order.note || '—'}</dd></div></dl></Section>{order.items.length > 0 && <Section title="Sipariş Kalemleri"><Table headers={['Ürün', 'Sipariş / Aktarılan / Kalan', 'Toplam', 'Kumaş', 'Gramaj']} rows={order.items.map((item) => [item.productName, itemUsage(item), item.totalQuantity, item.fabricName, item.gsm])} /></Section>}{creating && order.items.length > 0 && <Section title="Hangi Sipariş Kaleminden üretim oluşturulacak?"><Field label="Sipariş Kalemi"><select value={selectedItem} onChange={(e) => setSelectedItem(e.target.value)}><option value="">Kalem seçin</option>{order.items.map((item) => <option key={item.id} value={item.id}>{item.productName} · {item.totalQuantity} adet</option>)}</select></Field>{selectedItem && <NewProductionForm contacts={companies.data ?? []} orderCardId={order.id} orderItem={order.items.find((item) => item.id === selectedItem)} saved={() => { setCreating(false); setSelectedItem(''); resource.reload(); }} />}</Section>}{creating && order.items.length === 0 && companies.data && <NewProductionForm contacts={companies.data} orderCardId={order.id} saved={() => { setCreating(false); resource.reload(); }} />}<Section title="Üretim Kartları"><Table headers={['Üretim No', 'Marka', 'Ürün / Model', 'Durum', 'İşlem']} rows={order.productionCardIds.map((id) => cards.find((card) => card.id === id)).filter(Boolean).map((card) => [card!.productionNo, card!.brand ?? card!.cuttingSheet.brandSections[0]?.brandName ?? '—', card!.productName, card!.status, <a className="button ws-secondary" href={`/uretim/takip?id=${card!.id}`}>Üretim Kartını Aç</a>])} /></Section></Page>;
  return <Page title="Sipariş Kartları" error={resource.error || companies.error} loading={!resource.data || !companies.data}><div className="ws-tabs"><button className="button" onClick={() => setCreating(!creating)}>+ Sipariş Kartı Oluştur</button></div>{creating && <Section title="Yeni Sipariş Kartı">{quickCustomer && <CustomerQuickAdd done={(id) => { setNewCustomerId(id); setQuickCustomer(false); resource.reload(); }} />}<Form onDone={() => { setCreating(false); resource.reload(); }} onSubmit={async (form) => { await workflowRepository.createOrder({ orderType: text(form, 'orderType') as ProductionOrderCard['orderType'], customerId: text(form, 'customerId') || undefined, date: text(form, 'date'), note: text(form, 'note'), items }); }}><div className="ws-grid"><Field label="Sipariş Türü"><select name="orderType"><option>Ön Sipariş</option><option>Stok İçin Üretim</option></select></Field><Input label="Sipariş Tarihi *" name="date" type="date" value={today()} required /><Field label="Müşteri"><select name="customerId" value={newCustomerId} onChange={(e) => setNewCustomerId(e.target.value)}><option value="">Müşteri seçin</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.roles.includes('Hazır Giyim Müşterisi') ? '★ ' : ''}{c.name}</option>)}</select><button type="button" className="button ws-secondary" onClick={() => setQuickCustomer(!quickCustomer)}>+ Yeni Müşteri Ekle</button></Field><Field label="Genel Not"><textarea name="note" rows={2} /></Field></div><Section title="Sipariş Kalemleri">{items.map((item, index) => <ItemEditor key={index} item={item} definitions={definitions} update={(next) => setItems((prev) => prev.map((current, i) => i === index ? next : current))} remove={() => setItems((prev) => prev.filter((_, i) => i !== index))} />)}<button type="button" className="button ws-secondary" onClick={() => setItems((prev) => [...prev, emptyItem()])}>+ Ürün Ekle</button></Section></Form></Section>}<Table headers={['Sipariş No', 'Tür', 'Tarih', 'Sipariş Kalemi', 'Üretim Kartı', 'İşlem']} rows={(resource.data?.orders ?? []).map((o) => [<button className="button ws-secondary" onClick={() => setParams({ id: o.id })}>{o.orderNo}</button>, o.orderType, o.date, o.items.length, o.productionCardIds.length, <button className="button ws-secondary" onClick={() => setParams({ id: o.id })}>Detay</button>])} /></Page>;
}
