import { useState } from 'react';
import { Link, useLocation, useSearchParams } from 'react-router-dom';
import { workflowRepository } from '../../data/production';
import { productDefinitionRepository } from '../../data/productDefinitions';
import type { ProductionOrderItem } from '../../domain/productionWorkflow';
import { newestOrdersFirst, orderAllocation } from '../../domain/productionWorkflow';
import { OrderCardForm } from './OrderCardForm';
import { NewProductionForm } from './ProductionForms';
import { DueDate } from './DueDate';
import { Action, Field, Page, Section, Table, useCompanies, useResource } from '../shared/WorkshopUI';
import './production.css';

export function OrderCardsPage({ archived = false }: { archived?: boolean }) {
  const resource = useResource(async () => ({ orders: await workflowRepository.listOrders(), cards: await workflowRepository.list(), definitions: await productDefinitionRepository.list() }));
  const location = useLocation();
  const [editing, setEditing] = useState(false);
  const companies = useCompanies(); const [params, setParams] = useSearchParams(); const [creating, setCreating] = useState(false); const [selectedItem, setSelectedItem] = useState('');
  const order = resource.data?.orders.find((o) => o.id === params.get('id')); const definitions = resource.data?.definitions ?? []; const cards = resource.data?.cards ?? [];
  const itemUsage = (item: ProductionOrderItem) => orderAllocation(item, cards).map((r) => `${r.color}: ${r.quantity} / ${r.allocated} / ${r.remaining}`).join(' · ');
  const archiveAction = (o: NonNullable<typeof order>) => <Action run={() => workflowRepository.setOrderArchived(o.id, o.revision ?? 0, !o.archived)} done={() => { setParams({}); setCreating(false); setEditing(false); resource.reload(); }}>{o.archived ? 'Arşivden Çıkar' : 'Arşive At'}</Action>;
  const finish = () => { setCreating(false); setEditing(false); resource.reload(); };
  const form = (initial?: typeof order) => <OrderCardForm initial={initial} definitions={definitions} contacts={companies.data ?? []} reloadDefinitions={resource.reload} reloadContacts={companies.reload} done={finish} cancel={() => { setCreating(false); setEditing(false); }} />;
  if (order && editing) return <Page title={`${order.orderNo} · Sipariş Kartı`} error={resource.error || companies.error}>{form(order)}</Page>;
  if (order) return <Page title={`${order.orderNo} · Sipariş Kartı`} error={resource.error || companies.error} loading={!resource.data || !companies.data} reload={resource.reload}><div className="ws-tabs"><button className="button ws-secondary" onClick={() => setParams({})}>Sipariş Kartlarına Dön</button><button className="button ws-secondary" onClick={() => setEditing(true)}>Düzenle / Güncelle</button>{!order.archived && <button className="button" onClick={() => setCreating(!creating)}>+ Üretim Kartı Oluştur</button>}{archiveAction(order)}</div><Section title="Sipariş Bilgileri"><dl className="production-summary"><div><dt>Sipariş No</dt><dd>{order.orderNo}</dd></div><div><dt>Sipariş Türü</dt><dd>{order.orderType}</dd></div><div><dt>Tarih</dt><dd>{order.date}</dd></div><div><dt>Termin Tarihi</dt><dd><DueDate value={order.dueDate} /></dd></div><div><dt>Müşteri</dt><dd>{companies.data?.find((c) => c.id === order.customerId)?.name ?? '—'}</dd></div><div><dt>Not</dt><dd>{order.note || '—'}</dd></div></dl></Section>{order.items.length > 0 && <Section title="Sipariş Kalemleri"><Table headers={['Ürün Tanımı', 'Ürün / Model', 'Sipariş / Aktarılan / Kalan', 'Toplam', 'Kumaş', 'Gramaj']} rows={order.items.map((item) => [item.productName, item.modelName ?? item.productName, itemUsage(item), item.totalQuantity, item.fabricName, item.gsm])} /></Section>}{creating && order.items.length > 0 && <Section title="Hangi Sipariş Kaleminden üretim oluşturulacak?"><Field label="Sipariş Kalemi"><select value={selectedItem} onChange={(e) => setSelectedItem(e.target.value)}><option value="">Kalem seçin</option>{order.items.map((item) => <option key={item.id} value={item.id}>{item.modelName ?? item.productName} · {item.totalQuantity} adet</option>)}</select></Field>{selectedItem && <NewProductionForm key={selectedItem} records={cards} contacts={companies.data ?? []} orderCardId={order.id} orderItem={order.items.find((item) => item.id === selectedItem)} saved={() => { setCreating(false); setSelectedItem(''); resource.reload(); }} />}</Section>}{creating && order.items.length === 0 && companies.data && <NewProductionForm contacts={companies.data} orderCardId={order.id} saved={() => { setCreating(false); resource.reload(); }} />}<Section title="Üretim Kartları"><Table headers={['Üretim No', 'Marka', 'Ürün / Model', 'Durum', 'İşlem']} rows={order.productionCardIds.map((id) => cards.find((card) => card.id === id)).filter(Boolean).map((card) => [card!.productionNo, card!.brand ?? card!.cuttingSheet.brandSections[0]?.brandName ?? '—', card!.productName, card!.status, <Link className="button ws-secondary" to={`/uretim/takip?id=${card!.id}`}>Üretim Kartını Aç</Link>])} /></Section></Page>;
  return <Page title={archived ? 'Arşivlenen Siparişler' : 'Sipariş Kartları'} error={resource.error || companies.error} loading={!resource.data || !companies.data}>{location.state?.fromLegacyProduction && <p className="ws-hint" role="status">Üretim Kartı oluşturmak için önce bir Sipariş Kartı açın veya mevcut Sipariş Kartından Üretim Kartı oluşturun.</p>}<div className="ws-tabs">{!archived && <button className="button" onClick={() => setCreating(!creating)}>+ Sipariş Kartı Oluştur</button>}<Link className="button ws-secondary" to={archived ? '/uretim/siparisler' : '/uretim/arsivler'}>{archived ? 'Sipariş Kartları' : 'Arşivlenen Siparişler'}</Link></div>{creating && !archived && form()}<Table headers={['Sipariş No', 'Tür', 'Tarih', 'Termin Tarihi', 'Sipariş Kalemi', 'Üretim Kartı', 'İşlem']} rows={newestOrdersFirst(resource.data?.orders ?? []).filter((o) => !!o.archived === archived).map((o) => [<button className="button ws-secondary" onClick={() => setParams({ id: o.id })}>{o.orderNo}</button>, o.orderType, o.date, <DueDate value={o.dueDate} />, o.items.length, o.productionCardIds.length, <div className="ws-tabs"><button className="button ws-secondary" onClick={() => setParams({ id: o.id })}>Detay</button>{archiveAction(o)}</div>])} /></Page>;
}
