import { useState } from 'react';
import { Link } from 'react-router-dom';
import { productionRepository } from '../../data/production';
import type { PlanInput } from '../../domain/production';
import { planQuantity } from '../../domain/production';
import { today, displayDate, number } from '../products/model';
import { Action, Field, Form, Input, Page, Section, Select, Table, numeric, text, useResource } from '../shared/WorkshopUI';

export function PlansPage() {
  const resource = useResource(productionRepository.load); const [create, setCreate] = useState(false); const [colors, setColors] = useState([{ color: '', quantity: 0 }]);
  const done = () => { setCreate(false); resource.reload(); };
  return <Page title="Üretim Planı" error={resource.error} loading={!resource.data && !resource.error} reload={resource.reload}>
    <div className="ws-tabs"><button className="button ws-secondary" onClick={() => setCreate(false)}>Liste</button><button className="button" onClick={() => { setCreate(true); setColors([{ color: '', quantity: 0 }]); }}>Yeni Üretim Planı</button></div>
    {create ? <Form onDone={done} onSubmit={(f) => productionRepository.createPlan({ name: text(f, 'name'), brand: text(f, 'brand'), total: numeric(f, 'total'), colors, startDate: text(f, 'startDate'), deliveryDate: text(f, 'deliveryDate'), note: text(f, 'note'), status: text(f, 'status') as PlanInput['status'] })}><Section title="Plan Bilgileri"><div className="ws-grid"><Input label="Ürün *" name="name" required /><Input label="Marka" name="brand" /><Input label="Planlanan Toplam Adet *" name="total" type="number" min="1" step="1" required /><Input label="Planlanan Başlangıç *" name="startDate" type="date" value={today()} required /><Input label="Planlanan Teslim Tarihi" name="deliveryDate" type="date" /><Select label="Durum" name="status" values={['Planlandı', 'Beklemede', 'İptal']} /><Input label="Not" name="note" /></div></Section><Section title="Renk / Adet">{colors.map((color, i) => <div className="ws-row" key={i}><Field label="Renk *"><input required value={color.color} onChange={(e) => setColors(colors.map((c, j) => i === j ? { ...c, color: e.target.value } : c))} /></Field><Field label="Adet *"><input type="number" required min="1" step="1" value={color.quantity || ''} onChange={(e) => setColors(colors.map((c, j) => i === j ? { ...c, quantity: e.target.valueAsNumber } : c))} /></Field><button type="button" className="button ws-secondary" disabled={colors.length === 1} onClick={() => setColors(colors.filter((_, j) => i !== j))}>Satırı Kaldır</button></div>)}<button type="button" className="button ws-secondary" onClick={() => setColors([...colors, { color: '', quantity: 0 }])}>+ Renk Ekle</button><p className="ws-hint">Renk toplamı: {number(colors.reduce((sum, c) => sum + (c.quantity || 0), 0))}</p></Section></Form>
    : <Table headers={['Plan No', 'Ürün / Marka', 'Adet', 'Renk Dağılımı', 'Başlangıç', 'Teslim', 'Durum', 'Not', 'İşlemler']} rows={(resource.data?.plans ?? []).map((plan) => { const job = resource.data?.jobs.find((j) => j.planId === plan.id); return [plan.number, `${plan.name} / ${plan.brand}`, number(planQuantity(plan)), plan.colors.map((c) => `${c.color}: ${c.quantity}`).join(', '), displayDate(plan.startDate), plan.deliveryDate ? displayDate(plan.deliveryDate) : '—', job ? 'Üretime Başlatıldı' : plan.status, plan.note, job ? <Link className="button ws-secondary" to={`/uretim/devam-eden?is=${job.id}`}>İş Kartı</Link> : <><Action run={() => productionRepository.startPlan(plan.id, today())} done={done} disabled={plan.status !== 'Planlandı'}>Üretime Başlat</Action><Action run={() => productionRepository.setPlanStatus(plan.id, plan.status === 'Planlandı' ? 'Beklemede' : 'Planlandı')} done={done}>{plan.status === 'Planlandı' ? 'Beklemeye Al' : 'Planlandı Yap'}</Action><Action run={() => productionRepository.setPlanStatus(plan.id, 'İptal')} done={done}>İptal Et</Action></>]; })} />}
  </Page>;
}
