import { ProductionDialog } from './ProductionDialog';
import { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { orderDrafts } from '../../data/production/orderDrafts';
import type { OrderDraft } from '../../domain/productionOrder';
import { contactRepository } from '../../data/contacts';
import { productDefinitionRepository } from '../../data/productDefinitions';
import type { ProductDefinition } from '../../data/productDefinitions/repository';
import { orderRepository } from '../../data/production';
import { INTERNAL_CUSTOMER_ID } from '../../domain/productionPlan';
import { emptyEmbroidery, emptyPackaging } from '../../domain/productionOrder';
import type { ProductionBrand, ProductionOrder, OrderProductInput } from '../../domain/productionOrder';
import { defaultSizeDistribution } from '../../domain/productionWorkflow';
import { emptyContact } from '../contacts/model';
import type { Contact } from '../contacts/model';
import { today } from '../products/model';
import { Field, Form, Input, Section, text } from '../shared/WorkshopUI';
import { PlannedSizes } from './ProductionCardEditor';

export function CompactNotes({ value, onChange, title = 'Madde' }: { value: string[]; onChange: (v: string[]) => void; title?: string }) {
  return <div className="plan-note-list">{value.map((s, index) => <div className="plan-note-row" key={index}><Field label={`${title} ${index + 1}`}><input value={s} maxLength={2000} onChange={(e) => onChange(value.map((v, i) => i === index ? e.target.value : v))} /></Field><button type="button" className="button ws-secondary compact-control" aria-label={`${title} ${index + 1} sil`} onClick={() => onChange(value.filter((_, i) => i !== index))}>−</button></div>)}<button type="button" className="button ws-secondary compact-control" aria-label={`${title} ekle`} disabled={value.length >= 50} onClick={() => onChange([...value, ''])}>+</button></div>;
}
const newProduct = (): OrderProductInput => ({ productDefinitionId: '', modelName: '', brandId: '', fabricName: '', gsm: '', fabricProperties: '', colors: [{ color: '', quantity: 0 }], instructions: [''], sizeSeries: 'Yetişkin', sizeDistribution: defaultSizeDistribution('Yetişkin'), enabledStages: ['Kesim', 'Dikim', 'Ütü & Paket'], materials: [], embroidery: emptyEmbroidery(), printing: emptyEmbroidery(), dropShoulder: false, sideSlit: false, packaging: emptyPackaging() });

export function ProductionOrderForm({ initial, draft, customerId: presetCustomer, contacts, definitions, brands, done, cancel }: { initial?: ProductionOrder; draft?: OrderDraft; customerId?: string; contacts: Contact[]; definitions: ProductDefinition[]; brands: ProductionBrand[]; done: (id: string) => void; cancel: () => void }) {
  const [params, setParams] = useSearchParams();
  const [draftId] = useState(draft?.id ?? crypto.randomUUID());
  const revision = useRef(draft?.revision ?? 0), saved = useRef(false);
  const source = initial ?? draft?.input;
  const [general, setGeneral] = useState({ name: source?.name ?? '', date: source?.date ?? today(), dueDate: source?.dueDate ?? '', customerReference: source?.customerReference ?? '', customerNote: source?.customerNote ?? '', note: source?.note ?? '' });
  const [draftError, setDraftError] = useState('');
  const [product, setProduct] = useState<OrderProductInput>(source?.product ? { ...source.product, printing: source.product.printing ?? emptyEmbroidery() } : newProduct());
  const [customerId, setCustomerId] = useState(source?.customerId ?? presetCustomer ?? '');
  useEffect(() => {
    if (initial || saved.current) return;
    try { const next = orderDrafts.save(draftId, revision.current, { ...general, customerId, product }); revision.current = next.revision; setDraftError(''); if (params.get('draft') !== draftId) { const nextParams = new URLSearchParams(params); nextParams.set('draft', draftId); setParams(nextParams, { replace: true }); } }
    catch (e) { setDraftError(e instanceof Error ? e.message : 'Taslak kaydedilemedi.'); }
  }, [general, customerId, product, draftId, initial]);
  const [customerOptions, setCustomerOptions] = useState(contacts), [productOptions, setProductOptions] = useState(definitions), [brandOptions, setBrandOptions] = useState(brands);
  const [quick, setQuick] = useState(''); let savedId = initial?.id ?? '';
  const update = (next: Partial<OrderProductInput>) => setProduct((p) => ({ ...p, ...next }));
  const embroidery = product.enabledStages.includes('Nakış');
  return <div onChangeCapture={(event) => { const target = event.target as HTMLInputElement; if (Object.hasOwn(general, target.name)) setGeneral((g) => ({ ...g, [target.name]: target.value })); }}>
    {!initial && <p role={draftError ? 'alert' : 'status'}>{draftError || 'Taslak otomatik kaydedildi.'}</p>}
    {quick && <ProductionDialog title={`Yeni ${quick}`} close={() => setQuick('')}><Form label={`${quick} Kaydet`} cancel={() => setQuick('')} onDone={() => setQuick('')} onSubmit={async (f) => {
      const name = text(f, 'quickName');
      if (quick === 'Müşteri') { const c = await contactRepository.create({ ...emptyContact, name, roles: ['Hazır Giyim Müşterisi'] }); setCustomerOptions((list) => [...list, c]); setCustomerId(c.id); }
      else if (quick === 'Ürün') { const d = await productDefinitionRepository.save({ name, note: '', status: 'Aktif' }); setProductOptions((list) => [...list, d]); update({ productDefinitionId: d.id }); }
      else { const b = await orderRepository.createBrand(name); setBrandOptions((list) => [...list.filter((v) => v.id !== b.id), b]); update({ brandId: b.id }); }
    }}><Input label={`${quick} Adı *`} name="quickName" required /></Form></ProductionDialog>}
    <Form label={initial ? 'Siparişi Güncelle' : 'Siparişi Kaydet'} cancel={cancel} onDone={() => done(savedId)} onSubmit={async (f) => {
      const input = { name: text(f, 'name'), customerId, date: text(f, 'date'), dueDate: text(f, 'dueDate'), customerReference: text(f, 'customerReference'), customerNote: text(f, 'customerNote'), note: text(f, 'note'), product: { ...product, printing: { ...(product.printing ?? emptyEmbroidery()), notes: (product.printing?.notes ?? []).map((s) => s.trim()).filter(Boolean), colorNotes: product.printing?.colorNotes ?? [] }, instructions: product.instructions.map((s) => s.trim()).filter(Boolean), embroidery: { ...product.embroidery, notes: product.embroidery.notes.map((s) => s.trim()).filter(Boolean), colorNotes: product.embroidery.colorNotes } } };
      if (draftError) throw new Error(draftError);
      const o = initial ? await orderRepository.update(initial.id, initial.revision, input) : await orderRepository.create(input, draftId); savedId = o.id; saved.current = true;
    }}>
      <Section title="Müşteri Bilgileri"><div className="ws-grid"><Field label="Sipariş No"><input readOnly value={initial?.orderNo ?? 'Otomatik'} /></Field><div className="inline-choice"><Field label="Müşteri *"><select value={customerId} onChange={(e) => setCustomerId(e.target.value)} required><option value="">Müşteri seçin</option><option value={INTERNAL_CUSTOMER_ID}>ARGENT</option>{customerOptions.filter((c) => c.roles.includes('Hazır Giyim Müşterisi') && (c.status === 'Aktif' || c.id === customerId)).map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button type="button" className="button ws-secondary compact-control" aria-label="Yeni Müşteri" onClick={() => setQuick('Müşteri')}>+</button></div><Input label="Sipariş Adı *" name="name" value={general.name} required /><Input label="Müşteri Referans No" name="customerReference" value={general.customerReference} /><Field label="Müşteri Sipariş Notu"><textarea name="customerNote" maxLength={2000} defaultValue={general.customerNote} /></Field><div className="order-date-stack"><Input label="Sipariş Tarihi *" name="date" type="date" value={general.date} required /><Input label="Termin Tarihi *" name="dueDate" type="date" value={general.dueDate} required /></div></div></Section>
      <Section title="Ürün Bilgileri"><div className="ws-grid"><div className="inline-choice"><Field label="Ürün Türü / Tanımı *"><select value={product.productDefinitionId} required onChange={(e) => update({ productDefinitionId: e.target.value })}><option value="">Ürün seçin</option>{productOptions.filter((d) => d.status === 'Aktif' || d.id === product.productDefinitionId).map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><button type="button" className="button ws-secondary compact-control" aria-label="Yeni Ürün" onClick={() => setQuick('Ürün')}>+</button></div><Field label="Ürün / Model Adı *"><input required maxLength={200} value={product.modelName} onChange={(e) => update({ modelName: e.target.value })} /></Field><div className="inline-choice"><Field label="Marka *"><select required value={product.brandId} onChange={(e) => update({ brandId: e.target.value })}><option value="">Marka seçin</option>{brandOptions.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><button type="button" className="button ws-secondary compact-control" aria-label="Yeni Marka" onClick={() => setQuick('Marka')}>+</button></div><Field label="Kumaş Türü / Adı *"><input required value={product.fabricName} onChange={(e) => update({ fabricName: e.target.value })} /></Field><Field label="Gramaj"><input value={product.gsm} onChange={(e) => update({ gsm: e.target.value })} /></Field><Field label="Kumaş Özellikleri"><textarea value={product.fabricProperties} maxLength={2000} onChange={(e) => update({ fabricProperties: e.target.value })} /></Field></div></Section>
      <div className="order-colors-compact"><Section title="Renk ve Adetler">{product.colors.map((r, index) => <div className="order-color-editor" key={index}><Field label="Renk *"><input required value={r.color} onChange={(e) => update({ colors: product.colors.map((v, i) => i === index ? { ...v, color: e.target.value } : v), printing: { ...(product.printing ?? emptyEmbroidery()), colorNotes: (product.printing?.colorNotes ?? []).map((v) => v.color === r.color ? { ...v, color: e.target.value } : v) }, embroidery: { ...product.embroidery, colorNotes: product.embroidery.colorNotes.map((v) => v.color === r.color ? { ...v, color: e.target.value } : v) } })} /></Field><Field label="Adet *"><input type="number" required min={1} step={1} value={r.quantity || ''} onChange={(e) => update({ colors: product.colors.map((v, i) => i === index ? { ...v, quantity: Number(e.target.value) } : v) })} /></Field><button type="button" className="button ws-secondary compact-control" aria-label={`Renk ${index + 1} sil`} onClick={() => update({ colors: product.colors.filter((_, i) => i !== index) })}>−</button></div>)}<button type="button" className="button ws-secondary compact-control" aria-label="Renk ekle" onClick={() => update({ colors: [...product.colors, { color: '', quantity: 0 }] })}>+ Renk Ekle</button></Section></div>
      <Section title="Ürün Özellikleri"><div className="product-feature-choices"><YesNo label="Düşük Omuz" value={!!product.dropShoulder} onChange={(dropShoulder) => update({ dropShoulder })} /><YesNo label="Yırtmaç" value={!!product.sideSlit} onChange={(sideSlit) => update({ sideSlit })} /></div><h3>Diğer Ürün Özellikleri</h3><CompactNotes value={product.instructions} onChange={(instructions) => update({ instructions })} /></Section>
      <Section title="Seri / Paket Bilgileri"><PlannedSizes series={product.sizeSeries} value={product.sizeDistribution} onSeriesChange={(sizeSeries) => update({ sizeSeries })} onChange={(sizeDistribution) => update({ sizeDistribution })} /><div className="ws-grid"><Field label="Bir Pakette Kaç Ürün"><input type="number" min={1} step={1} value={product.packaging.unitsPerPack ?? ''} onChange={(e) => update({ packaging: { ...product.packaging, unitsPerPack: e.target.value ? Number(e.target.value) : undefined } })} /></Field>{(['type', 'sizeMode', 'note', 'labelingNote'] as const).map((key) => <Field key={key} label={{ type: 'Paket Tipi', sizeMode: 'Karışık Beden / Tek Beden', note: 'Özel Ambalaj Notu', labelingNote: 'Etiketleme Notu' }[key]}><input value={product.packaging[key]} onChange={(e) => update({ packaging: { ...product.packaging, [key]: e.target.value } })} /></Field>)}</div></Section>
<Section title="Nakış / Baskı Bilgileri"><Field label="İşlem Türü"><select aria-label="İşlem Türü" value={product.enabledStages.includes('Nakış') && product.enabledStages.includes('Baskı') ? 'İkisi de' : embroidery ? 'Nakış' : product.enabledStages.includes('Baskı') ? 'Baskı' : 'Yok'} onChange={(e) => update({ enabledStages: ['Kesim', ...(e.target.value === 'İkisi de' ? ['Nakış', 'Baskı'] as const : e.target.value === 'Yok' ? [] : [e.target.value as 'Nakış' | 'Baskı']), 'Dikim', 'Ütü & Paket'] })}>{['Yok', 'Nakış', 'Baskı', 'İkisi de'].map((t) => <option key={t}>{t}</option>)}</select></Field>{(['Nakış', 'Baskı'] as const).filter((type) => product.enabledStages.includes(type)).map((type) => {
  const key = type === 'Nakış' ? 'embroidery' : 'printing', info = product[key] ?? emptyEmbroidery();
  return <div key={type}><h3>{type}</h3><div className="ws-grid">{(['position', 'size', 'color'] as const).map((field) => <Field key={field} label={type + ' ' + { position: 'Konumu', size: 'Ölçüsü', color: 'Rengi' }[field]}><input maxLength={field === 'color' ? 200 : 2000} value={info[field] ?? ''} onChange={(e) => update({ [key]: { ...info, [field]: e.target.value } })} /></Field>)}</div><CompactNotes title={type + ' Notu'} value={info.notes} onChange={(notes) => update({ [key]: { ...info, notes } })} />{info.technicalNote && <Field label={type + ' Teknik Not'}><textarea maxLength={2000} value={info.technicalNote} onChange={(e) => update({ [key]: { ...info, technicalNote: e.target.value } })} /></Field>}</div>;
})}</Section>

      <Section title="Genel Not / Diğer Bilgiler"><Field label="Genel Not"><textarea name="note" maxLength={2000} defaultValue={general.note} /></Field></Section>
    </Form>
  </div>;
}

export function YesNo({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <div className="compact-choice" role="group" aria-label={label}><span>{label}:</span>{['Var', 'Yok'].map((v) => <button type="button" className="button ws-secondary" key={v} aria-pressed={value === (v === 'Var')} onClick={() => onChange(v === 'Var')}>{v}</button>)}</div>; }
