import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { planRepository, workflowRepository } from '../../data/production';
import { productDefinitionRepository } from '../../data/productDefinitions';
import { INTERNAL_CUSTOMER_ID, activeStages, completedQuantity, currentCompany, currentStage, deadlineText, isInternalPlan, itemGroup, itemStatus, planStages, planStatus, remainingDays, stageRecord } from '../../domain/productionPlan';
import type { PlanItem, PlanStage, ProductionPlan } from '../../domain/productionPlan';
import type { ProductionRecord } from '../../domain/productionWorkflow';
import { cutRows } from '../../domain/productionWorkflow';
import type { CuttingOrder } from '../../domain/cuttingWorkflow';
import type { Contact } from '../contacts/model';
import { Action, Field, Page, Section, Table, companyName, useCompanies, useResource } from '../shared/WorkshopUI';
import { ProductionPlanForm } from './ProductionPlanForm';
import { PlanSizes, PlanStages, PlanTechnicalPrint } from './PlanStages';
import { RecordActions } from './RecordActions';
import './production.css';

const customerName = (contacts: Contact[], id: string) => id === INTERNAL_CUSTOMER_ID ? 'ARGENT' : companyName(contacts, id);
function Deadline({ date }: { date: string }) { return <span className={(remainingDays(date) ?? 0) < 0 ? 'ws-error' : ''}>{date || '—'}<br /><small>{deadlineText(date)}</small></span>; }
const itemTotal = (i: PlanItem) => i.colors.reduce((n, r) => n + r.quantity, 0);

export function ProductionPlansPage({ mode = 'active' }: { mode?: 'active' | 'archive' | 'trash' }) {
  const resource = useResource(async () => ({ plans: await planRepository.list(), definitions: await productDefinitionRepository.list(), productions: await workflowRepository.list(), cuts: await workflowRepository.listCuttingOrders() }));
  const companies = useCompanies(); const contacts = companies.data ?? [];
  const [params, setParams] = useSearchParams();
  const [creating, setCreating] = useState(false), [editing, setEditing] = useState(false);
  const [view, setView] = useState('plan'), [filter, setFilter] = useState('Tümü'), [customer, setCustomer] = useState(''), [brand, setBrand] = useState(''), [stage, setStage] = useState('');
  const id = params.get('id') ?? params.get('is');
  // Historical bookmarks resolve to the same plan detail, including old production/cutting ids.
  const plan = resource.data?.plans.find((p) => p.id === id || p.legacyOrderId === id || p.items.some((i) => i.legacy?.productionIds.includes(id ?? '') || i.legacy?.cuttingIds.includes(id ?? '')));
  const selected = plan?.items.find((i) => i.id === params.get('item') || i.legacy?.productionIds.includes(id ?? '') || i.legacy?.cuttingIds.includes(id ?? '')) ?? plan?.items[0];
  const done = () => { setCreating(false); setEditing(false); resource.reload(); };
  const open = (p: ProductionPlan, i?: PlanItem) => { setCreating(false); setEditing(false); setParams({ id: p.id, ...(i ? { item: i.id } : {}) }); };
  const printType = params.get('print');
  const title = mode === 'archive' ? 'Arşiv' : mode === 'trash' ? 'Çöp Kutusu' : 'Üretim Planları';
  const visible = (resource.data?.plans ?? []).filter((p) => mode === 'trash' ? p.deleted : !p.deleted && !!p.archived === (mode === 'archive')).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const itemMatches = (i: PlanItem) => (filter === 'Tümü' || itemGroup(i) === filter) && (!brand || i.brand === brand) && (!stage || currentStage(i) === stage);
  const plans = visible.filter((p) => (!customer || p.customerId === customer) && (view === 'plan' ? (filter === 'Tümü' || planStatus(p) === filter) && ((!brand && !stage) || p.items.some((i) => (!brand || i.brand === brand) && (!stage || currentStage(i) === stage))) : p.items.some(itemMatches)));
  const back = () => { setParams({}); setCreating(false); setEditing(false); };
  return <Page title={title} loading={!resource.data || !companies.data} error={resource.error || companies.error} reload={resource.reload}>
    {plan && selected && (printType === 'Kesim' || printType === 'Nakış') ? <><div className="production-screen-only ws-tabs"><button className="button" onClick={() => window.print()}>Yazdır / PDF</button><button className="button ws-secondary" onClick={() => open(plan, selected)}>Plana Dön</button></div><PlanTechnicalPrint plan={plan} item={selected} type={printType} /></>
      : creating || (editing && plan) ? <ProductionPlanForm key={plan?.id ?? 'new'} initial={editing ? plan : undefined} definitions={resource.data?.definitions ?? []} contacts={contacts} done={(id) => { done(); setParams({ id }); }} cancel={back} />
      : plan ? <><div className="ws-tabs"><button className="button ws-secondary" onClick={back}>Planlara Dön</button><RecordActions kind="plan" record={plan} done={done} />{!plan.archived && !plan.deleted && !plan.items.some((i) => i.stages.length || i.legacy?.readOnly) && <button className="button ws-secondary" onClick={() => setEditing(true)}>Planı Düzenle</button>}</div>
        <Section title={`${plan.planNo} · ${plan.name}`}><dl className="production-summary">{[['Müşteri', customerName(contacts, plan.customerId)], ['Plan / Sipariş Tarihi', plan.date], ['Termin', plan.dueDate || '—'], ['Müşteri Referans No', plan.customerReference || '—'], ['Ürün Kalemi', String(plan.items.length)], ['Genel Durum', planStatus(plan)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>{plan.note}</p>{isInternalPlan(plan) && <p className="ws-hint">ARGENT · Kendi stokumuz için üretim</p>}</Section>
        <div className="ws-tabs" role="tablist" aria-label="Ürün Kalemleri">{plan.items.map((i, index) => <button role="tab" aria-selected={selected?.id === i.id} className="button ws-secondary" key={i.id} onClick={() => open(plan, i)}>{index + 1}. {i.brand} · {i.modelName}</button>)}</div>
        {selected ? <PlanItemDetail key={`${plan.id}:${plan.revision}:${selected.id}`} plan={plan} item={selected} contacts={contacts} productions={resource.data?.productions ?? []} cuts={resource.data?.cuts ?? []} done={done} print={(type) => setParams({ id: plan.id, item: selected.id, print: type })} /> : <p>Bu eski kayıtta ürün kalemi bulunmuyor. Planın genel bilgileri korunuyor.</p>}
      </> : id ? <p role="alert">Plan bulunamadı. <button onClick={back}>Planlara dön</button></p> : <>
        <div className="ws-tabs">{mode === 'active' && <button className="button" onClick={() => setCreating(true)}>+ Üretim Planı Oluştur</button>}<button className="button ws-secondary" aria-pressed={view === 'plan'} onClick={() => setView('plan')}>Plan Bazlı</button><button className="button ws-secondary" aria-pressed={view === 'item'} onClick={() => setView('item')}>Ürün Kalemi Bazlı</button></div>
        <div className="ws-filters"><Field label="Durum"><select value={filter} onChange={(e) => setFilter(e.target.value)}>{['Tümü', 'Planlama', 'Üretimde', 'Tamamlandı'].map((s) => <option key={s}>{s}</option>)}</select></Field><Field label="Müşteri"><select value={customer} onChange={(e) => setCustomer(e.target.value)}><option value="">Tümü</option>{[...new Set(visible.map((p) => p.customerId))].map((id) => <option key={id} value={id}>{customerName(contacts, id)}</option>)}</select></Field><Field label="Marka"><select value={brand} onChange={(e) => setBrand(e.target.value)}><option value="">Tümü</option>{[...new Set(visible.flatMap((p) => p.items.map((i) => i.brand)))].map((s) => <option key={s}>{s}</option>)}</select></Field><Field label="Mevcut Aşama"><select value={stage} onChange={(e) => setStage(e.target.value)}><option value="">Tümü</option>{[...planStages, 'Tamamlandı'].map((s) => <option key={s}>{s}</option>)}</select></Field></div>
        <p>{plans.length} plan · {plans.reduce((n, p) => n + (view === 'item' ? p.items.filter(itemMatches).length : p.items.length), 0)} ürün kalemi</p>
        {view === 'plan' ? <Table headers={['Plan No', 'Plan Adı', 'Müşteri', 'Tarih', 'Termin', 'Ürün Kalemi Sayısı', 'Toplam Adet', 'Genel Durum', 'İşlem']} rows={plans.map((p) => [p.planNo, p.name, customerName(contacts, p.customerId), p.date, <Deadline date={p.dueDate} />, p.items.length, p.items.reduce((n, i) => n + itemTotal(i), 0), planStatus(p), <button className="button ws-secondary" onClick={() => open(p)}>Detay</button>])} />
          : <Table headers={['Plan No', 'Müşteri', 'Marka', 'Ürün / Model', 'İstenen Adet', 'Mevcut Üretim Aşaması', 'Fasoncu / Firma', 'Termin', 'Kalan Gün', 'Durum', 'İşlem']} rows={plans.flatMap((p) => p.items.filter(itemMatches).map((i) => [p.planNo, customerName(contacts, p.customerId), i.brand, i.modelName, itemTotal(i), currentStage(i), companyName(contacts, currentCompany(i)), p.dueDate || '—', <Deadline date={p.dueDate} />, itemStatus(i), <button className="button ws-secondary" onClick={() => open(p, i)}>Detay</button>]))} />}
      </>}
  </Page>;
}

function PlanItemDetail({ plan, item, contacts, productions, cuts, done, print }: { plan: ProductionPlan; item: PlanItem; contacts: Contact[]; productions: ProductionRecord[]; cuts: CuttingOrder[]; done: () => void; print: (type: PlanStage) => void }) {
  const history = productions.filter((p) => item.legacy?.productionIds.includes(p.id));
  return <div className="plan-detail-grid"><div><Section title={`${item.brand} · ${item.modelName}`}><dl className="production-summary">{[['Müşteri', customerName(contacts, plan.customerId)], ['Marka', item.brand], ['Ürün Türü', item.productName], ['Ürün / Model', item.modelName], ['Kumaş', item.fabricName], ['Gramaj', item.gsm || '—'], ['Kumaş Özellikleri', item.fabricProperties || '—'], ['Termin', plan.dueDate || '—']].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><h3>Ortak Seri · {item.sizeSeries}</h3><PlanSizes item={item} /><Table headers={['Renk', 'İstenen Adet']} rows={item.colors.map((r) => [r.color, r.quantity])} /><h3>Ürün Talimatları</h3><ol>{item.instructions.map((s, i) => <li key={i}>{s}</li>)}</ol><h3>Gerekli Malzemeler / Aksesuarlar</h3><Table headers={['Malzeme Adı', 'Açıklama', 'Miktar']} rows={item.materials.map((m) => [m.name, m.description || '—', m.quantity || '—'])} /></Section>
    {item.legacy && <p className="ws-hint">{item.legacy.reason}</p>}
    <PlanStages plan={plan} item={item} contacts={contacts} done={done} print={print} />
    {itemStatus(item) === 'Tamamlandı' && !item.legacy?.readOnly && <Section title="Tamamlandı"><p>Tamamlanan miktar: {completedQuantity(item)}</p>{item.stockTransfer ? <p>Stoğa aktarıldı · {item.stockTransfer.date} {item.stockTransfer.stockIds.map((id) => <Link key={id} to={`/stok/urunler?islem=gecmis&id=${id}`}>Stok Kaydı </Link>)}</p> : isInternalPlan(plan) && !plan.archived && !plan.deleted && <Action run={() => planRepository.transfer(plan.id, plan.revision, item.id)} done={done}>Stoğa Aktar</Action>}</Section>}
    {item.legacy?.readOnly && <Section title="Korunan Üretim Geçmişi">{cuts.filter((c) => item.legacy?.cuttingIds.includes(c.id)).map((c) => <div key={c.id}><h3>Kesim · {c.cuttingNo} · {companyName(contacts, c.cutterCompanyId)}</h3><Table headers={['Renk', 'İstenen', 'Gerçek Kesim', 'Top', 'Kg']} rows={c.requested.map((r) => { const actual = c.result?.rows.find((v) => v.color === r.color); return [r.color, r.quantity, actual?.quantity ?? '—', actual?.rollCount ?? '—', actual?.kg ?? '—']; })} /></div>)}{history.map((p) => <div key={p.id}><h3>{p.productionNo} · {p.brand} · {p.deleted ? 'Çöp Kutusunda' : p.status}</h3><Table headers={['Marka', 'Renk', 'Kesilen Adet']} rows={cutRows(p).map((r) => [r.brandName, r.color, r.quantity])} /><Table headers={['Aşama', 'Firma', 'Başlangıç', 'Gelen', 'Durum', 'Not']} rows={p.productionStages.map((s) => [s.processType, companyName(contacts, s.companyId), s.sentQuantity, s.returnedQuantity, s.status, s.note])} />{p.completion && <p>Tamamlanan: {p.completion.good} · Fire: {p.completion.waste}</p>}{p.stockTransfer ? <p>Stoğa aktarıldı · {p.stockTransfer.date}</p> : p.completion && isInternalPlan(plan) && !plan.archived && !plan.deleted && !p.deleted && <Action run={() => workflowRepository.transfer(p.id)} done={done}>Stoğa Aktar</Action>}</div>)}</Section>}
  </div><aside className="plan-status-panel"><Section title="Üretim Durumu"><p><strong>Mevcut Durum:</strong> {itemStatus(item)}</p><p><strong>Mevcut Firma:</strong> {companyName(contacts, currentCompany(item))}</p><p><strong>Termin:</strong> <Deadline date={plan.dueDate} /></p><ol className="plan-process">{activeStages(item).map((s) => <li key={s} className={stageRecord(item, s)?.result ? 'done' : stageRecord(item, s) ? 'current' : ''}><strong>{s}</strong><span>{stageRecord(item, s)?.result ? 'Tamamlandı' : stageRecord(item, s) ? 'İşlemde' : 'Bekliyor'}</span></li>)}<li className={itemStatus(item) === 'Tamamlandı' ? 'done' : ''}>Tamamlandı</li></ol></Section></aside></div>;
}
