import { useState } from 'react';
import { contactRepository } from '../../data/contacts';
import { productDefinitionRepository } from '../../data/productDefinitions';
import type { ProductDefinition } from '../../data/productDefinitions/repository';
import { orderRepository } from '../../data/production';
import { INTERNAL_CUSTOMER_ID } from '../../domain/productionPlan';
import { emptyEmbroidery, emptyPackaging } from '../../domain/productionOrder';
import type { ProductionBrand, ProductionOrder, OrderProductInput } from '../../domain/productionOrder';
import { defaultSizeDistribution } from '../../domain/productionWorkflow';
import { emptyContact } from '../contacts/model';
import type { Contact } from '../contacts/model';
import { today } from '../products/model';
import { Field, Form, Input, Section, text } from '../shared/WorkshopUI';
import { PlannedSizes } from './ProductionCardEditor';

export function CompactNotes({ value, onChange, title = 'Madde' }: { value: string[]; onChange: (v: string[]) => void; title?: string }) {
  return <div className="plan-note-list">{value.map((s, index) => <div className="plan-note-row" key={index}><Field label={`${title} ${index + 1}`}><input value={s} maxLength={2000} onChange={(e) => onChange(value.map((v, i) => i === index ? e.target.value : v))} /></Field><button type="button" className="button ws-secondary compact-control" aria-label={`${title} ${index + 1} sil`} onClick={() => onChange(value.filter((_, i) => i !== index))}>−</button></div>)}<button type="button" className="button ws-secondary compact-control" aria-label={`${title} ekle`} disabled={value.length >= 50} onClick={() => onChange([...value, ''])}>+</button></div>;
}
const newProduct = (): OrderProductInput => ({ productDefinitionId: '', modelName: '', brandId: '', fabricName: '', gsm: '', fabricProperties: '', colors: [{ color: '', quantity: 0 }], instructions: [''], sizeSeries: 'Yetişkin', sizeDistribution: defaultSizeDistribution('Yetişkin'), enabledStages: ['Kesim', 'Dikim', 'Ütü & Paket'], materials: [], embroidery: emptyEmbroidery(), packaging: emptyPackaging() });

export function ProductionOrderForm({ initial, customerId: presetCustomer, contacts, definitions, brands, done, cancel }: { initial?: ProductionOrder; customerId?: string; contacts: Contact[]; definitions: ProductDefinition[]; brands: ProductionBrand[]; done: (id: string) => void; cancel: () => void }) {
  const [product, setProduct] = useState<OrderProductInput>(initial?.product ?? newProduct());
  const [customerId, setCustomerId] = useState(initial?.customerId ?? presetCustomer ?? '');
  const [customerOptions, setCustomerOptions] = useState(contacts), [productOptions, setProductOptions] = useState(definitions), [brandOptions, setBrandOptions] = useState(brands);
  const [quick, setQuick] = useState(''); let savedId = initial?.id ?? '';
  const update = (next: Partial<OrderProductInput>) => setProduct((p) => ({ ...p, ...next }));
  const embroidery = product.enabledStages.includes('Nakış');
  return <>
    {quick && <Section title={`Yeni ${quick}`}><Form label={`${quick} Kaydet`} cancel={() => setQuick('')} onDone={() => setQuick('')} onSubmit={async (f) => {
      const name = text(f, 'quickName');
      if (quick === 'Müşteri') { const c = await contactRepository.create({ ...emptyContact, name, roles: ['Hazır Giyim Müşterisi'] }); setCustomerOptions((list) => [...list, c]); setCustomerId(c.id); }
      else if (quick === 'Ürün') { const d = await productDefinitionRepository.save({ name, note: '', status: 'Aktif' }); setProductOptions((list) => [...list, d]); update({ productDefinitionId: d.id }); }
      else { const b = await orderRepository.createBrand(name); setBrandOptions((list) => [...list.filter((v) => v.id !== b.id), b]); update({ brandId: b.id }); }
    }}><Input label={`${quick} Adı *`} name="quickName" required /></Form></Section>}
    <Form label={initial ? 'Siparişi Güncelle' : 'Siparişi Oluştur'} cancel={cancel} onDone={() => done(savedId)} onSubmit={async (f) => {
      const input = { name: text(f, 'name'), customerId, date: text(f, 'date'), dueDate: text(f, 'dueDate'), customerReference: text(f, 'customerReference'), customerNote: text(f, 'customerNote'), note: text(f, 'note'), product: { ...product, instructions: product.instructions.map((s) => s.trim()).filter(Boolean), embroidery: { ...product.embroidery, notes: product.embroidery.notes.map((s) => s.trim()).filter(Boolean), colorNotes: product.embroidery.colorNotes.filter((r) => product.colors.some((c) => c.color === r.color)) } } };
      const o = initial ? await orderRepository.update(initial.id, initial.revision, input) : await orderRepository.create(input); savedId = o.id;
    }}>
      <Section title="Müşteri Bilgileri"><div className="ws-grid"><Field label="Sipariş No"><input readOnly value={initial?.orderNo ?? 'Otomatik'} /></Field><Field label="Müşteri *"><select value={customerId} onChange={(e) => setCustomerId(e.target.value)} required><option value="">Müşteri seçin</option><option value={INTERNAL_CUSTOMER_ID}>ARGENT</option>{customerOptions.filter((c) => c.roles.includes('Hazır Giyim Müşterisi') && (c.status === 'Aktif' || c.id === customerId)).map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button type="button" className="button ws-secondary" onClick={() => setQuick('Müşteri')}>+ Yeni Müşteri</button><Input label="Sipariş Adı *" name="name" value={initial?.name} required /><Input label="Sipariş Tarihi *" name="date" type="date" value={initial?.date ?? today()} required /><Input label="Termin Tarihi *" name="dueDate" type="date" value={initial?.dueDate} required /><Input label="Müşteri Referans No" name="customerReference" value={initial?.customerReference} /><Field label="Müşteri / Sipariş Notu"><textarea name="customerNote" maxLength={2000} defaultValue={initial?.customerNote} /></Field></div></Section>
      <Section title="Ürün Bilgileri"><div className="ws-grid"><Field label="Ürün Türü / Tanımı *"><select value={product.productDefinitionId} required onChange={(e) => update({ productDefinitionId: e.target.value })}><option value="">Ürün seçin</option>{productOptions.filter((d) => d.status === 'Aktif' || d.id === product.productDefinitionId).map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><button type="button" className="button ws-secondary" onClick={() => setQuick('Ürün')}>+ Yeni Ürün</button><Field label="Ürün / Model Adı *"><input required maxLength={200} value={product.modelName} onChange={(e) => update({ modelName: e.target.value })} /></Field><Field label="Marka *"><select required value={product.brandId} onChange={(e) => update({ brandId: e.target.value })}><option value="">Marka seçin</option>{brandOptions.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><button type="button" className="button ws-secondary" onClick={() => setQuick('Marka')}>+ Yeni Marka</button><Field label="Kumaş Türü / Adı *"><input required value={product.fabricName} onChange={(e) => update({ fabricName: e.target.value })} /></Field><Field label="Gramaj"><input value={product.gsm} onChange={(e) => update({ gsm: e.target.value })} /></Field><Field label="Kumaş Özellikleri"><textarea value={product.fabricProperties} maxLength={2000} onChange={(e) => update({ fabricProperties: e.target.value })} /></Field></div></Section>
      <Section title="Renk ve Adetler">{product.colors.map((r, index) => <div className="order-color-editor" key={index}><Field label="Renk *"><input required value={r.color} onChange={(e) => update({ colors: product.colors.map((v, i) => i === index ? { ...v, color: e.target.value } : v), embroidery: { ...product.embroidery, colorNotes: product.embroidery.colorNotes.map((v) => v.color === r.color ? { ...v, color: e.target.value } : v) } })} /></Field><Field label="Adet *"><input type="number" required min={1} step={1} value={r.quantity || ''} onChange={(e) => update({ colors: product.colors.map((v, i) => i === index ? { ...v, quantity: Number(e.target.value) } : v) })} /></Field><button type="button" className="button ws-secondary compact-control" aria-label={`Renk ${index + 1} sil`} onClick={() => update({ colors: product.colors.filter((_, i) => i !== index) })}>−</button></div>)}<button type="button" className="button ws-secondary compact-control" aria-label="Renk ekle" onClick={() => update({ colors: [...product.colors, { color: '', quantity: 0 }] })}>+</button></Section>
      <Section title="Ürün Özellikleri"><CompactNotes value={product.instructions} onChange={(instructions) => update({ instructions })} /></Section>
      <Section title="Seri / Beden Bilgisi"><PlannedSizes series={product.sizeSeries} value={product.sizeDistribution} onSeriesChange={(sizeSeries) => update({ sizeSeries })} onChange={(sizeDistribution) => update({ sizeDistribution })} /></Section>
      <Section title="Nakış Bilgileri"><Field label="Nakış Var / Yok"><select value={embroidery ? 'Var' : 'Yok'} onChange={(e) => update({ enabledStages: e.target.value === 'Var' ? [...product.enabledStages, 'Nakış'] : product.enabledStages.filter((s) => s !== 'Nakış') })}><option>Yok</option><option>Var</option></select></Field>{embroidery && <><CompactNotes title="Nakış Notu" value={product.embroidery.notes} onChange={(notes) => update({ embroidery: { ...product.embroidery, notes } })} /><div className="ws-grid">{(['position', 'size', 'technicalNote'] as const).map((key) => <Field key={key} label={{ position: 'Logo / Nakış Konumu', size: 'Nakış Ölçüsü', technicalNote: 'Diğer Teknik Notlar' }[key]}><input value={product.embroidery[key]} onChange={(e) => update({ embroidery: { ...product.embroidery, [key]: e.target.value } })} /></Field>)}</div>{product.colors.map((r, index) => <Field key={index} label={`${r.color || 'Renk'} Nakış Açıklaması`}><input value={product.embroidery.colorNotes.find((v) => v.color === r.color)?.note ?? ''} onChange={(e) => update({ embroidery: { ...product.embroidery, colorNotes: [...product.embroidery.colorNotes.filter((v) => v.color !== r.color), { color: r.color, note: e.target.value }] } })} /></Field>)}</>}</Section>
      <Section title="Paket / Ambalaj Bilgisi"><div className="ws-grid"><Field label="Bir Pakette Kaç Ürün"><input type="number" min={1} step={1} value={product.packaging.unitsPerPack ?? ''} onChange={(e) => update({ packaging: { ...product.packaging, unitsPerPack: e.target.value ? Number(e.target.value) : undefined } })} /></Field>{(['type', 'sizeMode', 'note', 'labelingNote'] as const).map((key) => <Field key={key} label={{ type: 'Paket Tipi', sizeMode: 'Karışık Beden / Tek Beden', note: 'Özel Ambalaj Notu', labelingNote: 'Etiketleme Notu' }[key]}><input value={product.packaging[key]} onChange={(e) => update({ packaging: { ...product.packaging, [key]: e.target.value } })} /></Field>)}</div></Section>
      <Section title="Genel Not / Diğer Bilgiler"><Field label="Genel Not"><textarea name="note" maxLength={2000} defaultValue={initial?.note} /></Field><label><input type="checkbox" checked={product.enabledStages.includes('Baskı')} onChange={(e) => update({ enabledStages: e.target.checked ? [...product.enabledStages, 'Baskı'] : product.enabledStages.filter((s) => s !== 'Baskı') })} /> Baskı var</label></Section>
    </Form>
  </>;
}
